const ACTION_CELL_LEFT_CLICKED = 'ACTION_CELL_LEFT_CLICKED';
const ACTION_CELL_RIGHT_CLICKED = 'ACTION_CELL_RIGHT_CLICKED';
const ACTION_GAME_STARTED = 'ACTION_GAME_STARTED';
const ACTION_GAME_RESET = 'ACTION_GAME_RESET';

export {
  ACTION_CELL_LEFT_CLICKED,
  ACTION_CELL_RIGHT_CLICKED,
  ACTION_GAME_STARTED,
  ACTION_GAME_RESET,
};

/**
 * @typedef {(
 *      ACTION_CELL_LEFT_CLICKED
 *    | ACTION_CELL_RIGHT_CLICKED
 *    | ACTION_GAME_STARTED
 *    | ACTION_GAME_RESET
 * )} Action
 */
